name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  switch-build:
    name: Switch build

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build commands inside Docker container
        run: |
          cmake --preset switch
          cmake --build --preset switch

      - name: Create zip with binaries
        run: |
          DATE_TIME=$(date +'%Y-%m-%d_%H-%M-%S')
          zip -j "fallout2-ce_${DATE_TIME}.zip" build/switch/fallout2-ce.nro

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fallout2-ce
          path: |
            fallout2-ce_*.zip
