name: Release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  switch:
    name: Switch Release build

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      env:
        F2_VERSION: ${{ github.event.release.tag_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build commands inside Docker container
        run: |
          cmake --preset switch
          cmake --build --preset switch

      - name: Upload binaries
        run: |
          cd build
          gh release upload ${{ github.event.release.tag_name }} fallout2-ce.nro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
